#      __   ____  ____   __   ____  ____   __    ___  ____ 
#     / _\ (  __)(  _ \ /  \ / ___)(  _ \ / _\  / __)(  __)
#    /    \ ) _)  )   /(  O )\___ \ ) __//    \( (__  ) _) 
#    \_/\_/(____)(__\_) \__/ (____/(__)  \_/\_/ \___)(____)

# Place a copy of this config to ~/.aerospace.toml

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layouts
accordion-padding = 40
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# macOS "Hide application" toggle
automatically-unhide-macos-hidden-apps = false

# Keyboard mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows and monitor edges
[gaps]
inner.horizontal = 10
inner.vertical   = 10
outer.left       = 8
outer.right      = 8
outer.top        = 12
outer.bottom     = 8

# Main binding mode
[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Workspaces
#alt-1 = 'workspace 1'
#alt-2 = 'workspace 2'
#alt-3 = 'workspace 3'
#alt-4 = 'workspace 4'
#alt-5 = 'workspace 5'
#alt-6 = 'workspace 6'
#alt-7 = 'workspace 7'
#alt-8 = 'workspace 8'
#alt-9 = 'workspace 9'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'
alt-f = 'workspace F'
alt-g = 'workspace G'
alt-i = 'workspace I'
alt-m = 'workspace M'
alt-n = 'workspace N'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-q = 'workspace Q'
alt-r = 'workspace R'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-u = 'workspace U'
alt-v = 'workspace V'
alt-w = 'workspace W'
alt-x = 'workspace X'
alt-y = 'workspace Y'
alt-z = 'workspace Z'

# Move nodes between workspaces
#alt-shift-1 = 'move-node-to-workspace 1'
#alt-shift-2 = 'move-node-to-workspace 2'
#alt-shift-3 = 'move-node-to-workspace 3'
#alt-shift-4 = 'move-node-to-workspace 4'
#alt-shift-5 = 'move-node-to-workspace 5'
#alt-shift-6 = 'move-node-to-workspace 6'
#alt-shift-7 = 'move-node-to-workspace 7'
#alt-shift-8 = 'move-node-to-workspace 8'
#alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-f = 'move-node-to-workspace F'
alt-shift-g = 'move-node-to-workspace G'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-m = 'move-node-to-workspace M'
alt-shift-n = 'move-node-to-workspace N'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-r = 'move-node-to-workspace R'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-v = 'move-node-to-workspace V'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-x = 'move-node-to-workspace X'
alt-shift-y = 'move-node-to-workspace Y'
alt-shift-z = 'move-node-to-workspace Z'

# Move into service mode from standard
    alt-shift-semicolon = 'mode service'
#allows resize mode.
    alt-shift-0= 'mode resize'


[workspace-to-monitor-force-assignment]
T = 'main'
B = 'main'
G = 'secondary'
O = 'secondary'
C = 'secondary'
W = 'secondary'
E = 'secondary'
R = 'secondary'

#alt-tab = 'workspace-back-and-forth'
#alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

#alt-shift-semicolon = 'mode service'

# Service binding mode
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

[mode.resize.binding]
   h = 'resize width -50'
   j = 'resize height +50'
   k = 'resize height -50'
   l = 'resize width +50'
   enter = 'mode main'
   esc = 'mode main'

# Example mapping (keep commented)
# if.app-id = 'com.github.wez.wezterm'
# run = "move-node-to-workspace T"


# app â†’ workspace rules go LAST and contain only if.* + run
[[on-window-detected]]
if.app-id = "com.microsoft.Outlook"
run = "move-node-to-workspace O"

[[on-window-detected]]
if.app-id = "com.microsoft.teams2"
run = "move-node-to-workspace C"

[[on-window-detected]]
if.app-id = "com.apple.Terminal"
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = "com.openai.chat"
run = "move-node-to-workspace G"

[[on-window-detected]]
if.app-id = "com.microsoft.edgemac"
run = "move-node-to-workspace B"
